production:
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
  endpoint: <%= ENV['S3_ENDPOINT_DOMAIN'] %>
  #signature_version: 2 # some storage backends are compatible only with signature version 2
