# Sample configuration file for Sidekiq.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:timeout: 30
:queues:
  - default
  - telegram # Used for telegram messaging
  - index_queue # Used for redmine_elasticsearch https://github.com/centosadmin/redmine_elasticsearch
